name: Deploy Static Website

on:
  push:
    branches: [ main, master ] # Sostituisci con il nome del tuo branch principale

# Permessi necessari per l'autenticazione con GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Evita build concorrenti simultanee
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Carica i file statici
        uses: actions/upload-pages-artifact@v3
        with:
          # Indica a GitHub di prendere i file dentro _site
          path: '_site'

      - name: Pubblica su GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
